version: '3.8'
services:
  tweet:
    image: <...>/twittah-tweet:latest
    environment:
      POSTGRES_DSN: $TWEET_POSTGRES_DSN
      REDIS_ADDR: $TWEET_REDIS_ADDR
      KAFKA_BROKERS: $KAFKA_BROKERS
      KAFKA_GROUP_ID: $KAFKA_GROUP_ID
      SERVICE_PORT: $TWEET_SERVICE_PORT
      TIMELINE_TTL_HOURS: $TIMELINE_TTL_HOURS
    ports:
      - "8084:8084"

  user:
    image: <...>/twittah-user:latest
    environment:
      POSTGRES_DSN: $USER_POSTGRES_DSN
      REDIS_ADDR: $USER_REDIS_ADDR
      KAFKA_BROKERS: $KAFKA_BROKERS
      USER_SERVICE_PORT: $USER_SERVICE_PORT
    ports:
      - "8082:8082"

  auth:
    image: <...>/twittah-auth:latest
    environment:
      POSTGRES_DSN: $AUTH_POSTGRES_DSN
      KAFKA_BROKERS: $KAFKA_BROKERS
      AUTH_PORT: $AUTH_PORT
    ports:
      - "8083:8083"

  gateway:
    image: <...>/twittah-gateway:latest
    environment:
      KAFKA_BROKERS: $KAFKA_BROKERS
      GATEWAY_PORT: $GATEWAY_PORT
      KAFKA_FOLLOWS_TOPIC: $KAFKA_FOLLOWS_TOPIC
      KAFKA_USER_TOPIC: $KAFKA_USER_TOPIC
    ports:
      - "8081:8081"