// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Drivello/Twittah/services/tweet/ent/schema"
	"github.com/Drivello/Twittah/services/tweet/ent/tweet"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tweetFields := schema.Tweet{}.Fields()
	_ = tweetFields
	// tweetDescAuthorID is the schema descriptor for author_id field.
	tweetDescAuthorID := tweetFields[0].Descriptor()
	// tweet.AuthorIDValidator is a validator for the "author_id" field. It is called by the builders before save.
	tweet.AuthorIDValidator = tweetDescAuthorID.Validators[0].(func(string) error)
	// tweetDescContent is the schema descriptor for content field.
	tweetDescContent := tweetFields[1].Descriptor()
	// tweet.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	tweet.ContentValidator = tweetDescContent.Validators[0].(func(string) error)
	// tweetDescCreatedAt is the schema descriptor for created_at field.
	tweetDescCreatedAt := tweetFields[2].Descriptor()
	// tweet.DefaultCreatedAt holds the default value on creation for the created_at field.
	tweet.DefaultCreatedAt = tweetDescCreatedAt.Default.(func() time.Time)
}
